package com.demo.parkease.entity;

import jakarta.persistence.*;
import lombok.*;

/**
 * Maps to the `parking_slots` table.
 *
 * DB schema columns:
 *   id, slot_code, vehicle_type, cost_per_hour,
 *   slot_status, disabled, parking_id
 *
 * Note: DB column is `slot_status` (not `status`) — mapped with @Column(name=...)
 */
@Entity
@Table(name = "parking_slots")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ParkingSlot {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Human-readable slot code generated by ParkingService.
     * Pattern: {PREFIX}-{nn}  e.g. CAR-01, BIKE-03, LRG-01, SML-02
     */
    @Column(name = "slot_code", nullable = false, length = 20)
    private String slotCode;

    @Column(name = "vehicle_type", nullable = false)
    @Enumerated(EnumType.STRING)
    private VehicleType vehicleType;

    @Column(name = "cost_per_hour", nullable = false)
    private Double costPerHour;

    /**
     * DB column is named `slot_status` to avoid conflict with
     * the reserved word `status` in some MySQL versions.
     */
    @Column(name = "slot_status", nullable = false)
    @Enumerated(EnumType.STRING)
    @Builder.Default
    private SlotStatus status = SlotStatus.AVAILABLE;

    /**
     * Owner can disable a slot (e.g. under repair).
     * Disabled slots → status forced to MAINTENANCE, not bookable.
     */
    @Column(nullable = false)
    @Builder.Default
    private Boolean disabled = false;

    /** The parking lot this slot belongs to. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parking_id", nullable = false)
    private Parking parking;
}